### PR TITLE
Fix GUI resizing and overflow scaling issues

### LINKED ISSUE #127: GUI Scaling Cuts Off Remark
Image

GUI can go scale smaller than remarks section, causing remarks to be cut off at the right

### LINKED ISSUE #128: GUI Not Using Full Possible Size
Image

Remarks still has a lot of plenty unused space on the right

### LINKED ISSUE #132: GUI Tag Goes Through Remark If Too Long
Image

### LINKED ISSUE #142: Need a dollar sign after the clearing price
We need a dollar sign to show the currency

### PR DESCRIPTION
**Pull request by TanJieHaoAmos**
Fix #127 
Fix #128 
Fix #132 
Fix #142

### CODE REVIEW

File: src/main/java/seedu/finclient/ui/MainWindow.java [hunk 1]
```diff
@@ -124,7 +124,7 @@ private void setAccelerator(MenuItem menuItem, KeyCombination keyCombination) {
      */
     void fillInnerParts() {
 
-        priceLabel.setText("Clearing Price: " + logic.getClearingPrice().orElse(0.0));
+        priceLabel.setText("Clearing Price: S$" + logic.getClearingPrice().orElse(0.0));
```
Comment (RickyHFR) [inline src/main/java/seedu/finclient/ui/MainWindow.java:127]: Nice.

**Review by RickyHFR — APPROVED** [review]
LGTM.
