### PR TITLE
Fix remark related alpha bug

### LINKED ISSUE #139: timestamp in remark allows invalid dates

### PR DESCRIPTION
**Pull request by ki1r0**
fix #139

### CODE REVIEW

File: src/main/java/seedu/finclient/logic/commands/CommandType.java [hunk 1]
```diff
@@ -0,0 +1,9 @@
+package seedu.finclient.logic.commands;
+
+/**
+ * Represents the context in which a command is being parsed or executed.
+ */
+public enum CommandType {
+    ADD,
+    EDIT
+}
```
Comment (hyizhak) [inline src/main/java/seedu/finclient/logic/commands/CommandType.java:9]: This code seems confusing to me. If it is necessary I think this should be in-place far before

File: src/main/java/seedu/finclient/logic/parser/ParserUtil.java [hunk 2]
```diff
@@ -181,13 +186,31 @@ public static Order parseOrder(String order, String amount, String price) throws
...
+        String text = parts[0].trim();
+        if (!Remark.isValidRemark(text)) {
             throw new ParseException(Remark.MESSAGE_CONSTRAINTS);
         }
-        return new Remark(trimmedRemark);
+        Optional<LocalDateTime> ts = Optional.empty();
+        if (parts.length > 1) {
+            String dateTimeStr = parts[1].trim();
+            String regexPattern = "\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}";
+            if (!dateTimeStr.matches(regexPattern)) {
```
Comment (hyizhak) [inline src/main/java/seedu/finclient/logic/parser/ParserUtil.java:203]: I think this can be slightly refactored to use DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm")

**Review by hyizhak — COMMENTED** [review]
Please check my comments and I think moving the CommandType really helps for a clearer structure.

**Comment by hyizhak** [comment]
Looks good to me now. Thanks!
